#!/usr/bin/env bash
# Add nginx user
useradd -r -s /sbin/nologin nginx
# Change ownership of Nginx directories
chown -R nginx:nginx /var/log/nginx /var/lib/nginx
# Nginx configuration file path
nginx_conf="/etc/nginx/nginx.conf"  # Update this if your configuration file is in a different location
# Change user in Nginx configuration
sed -i 's/user\s\+\w\+/user nginx/' $nginx_conf
# Change Nginx to listen on port 8080
sed -i 's/listen\s\+80;/listen 8080;/' $nginx_conf
# Restart Nginx
service nginx restart
