#!/usr/bin/env bash
# Set the Nginx user to nginx
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
# Change the listening port to 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
# Restart Nginx to apply changes
service nginx restart
# Display the Nginx status to verify changes
service nginx status
